### ISSUE TITLE
Add to homebrew

### ISSUE THREAD

**Issue by kareman** [kareman/SwiftShell#10]
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md

**Comment by kareman** [comment]
I'm hoping someone with experience with Homebrew can implement this one.

**Comment by tanmayb123** [comment]
I think homebrew is more for command line packages, but I could be wrong. Maybe CocoaPods and Carthage would better suit for SwiftShell?

**Comment by kareman** [comment]
You're right, but Swiftshell is both a framework and a shell script  which you call in the shebang at the top of your swift scripts. The problem now is that all swift frameworks have to be recompiled for every version of the compiler, so in its current version swiftshell isn't a good fit for homebrew. So I'll close this until there is a solution to this problem.
