### ISSUE TITLE
How to execute rm -rf /xxx/*

### ISSUE THREAD

**Issue by cdwmhcc** [kareman/SwiftShell#102]
`run("rm", "-rf", "/xxx/swift shell/a.txt")` is working,
But `run("rm", "-rf", "/xxx/swift shell/*")` it does not work

what should I do?

**Comment by kareman** [comment]
In order to use `*` you must use bash, like this: `run(bash: "rm -rf /xxx/swift\ shell/*")`.  Be careful with that command though, it deletes everything in that folder.

**Comment by cdwmhcc** [comment]
> In order to use `*` you must use bash, like this: `run(bash: "rm -rf /xxx/swift\ shell/*")`. Be careful with that command though, it deletes everything in that folder.

Thanks for your help.

I tried it and it didn't work. I now use a for loop to generate relative paths and it works.

**Comment by cdwmhcc** [comment]
Use:

`let all:Bool = true`
`runAsync(bash: "rm '\(path)'\(all ? "/*" : "")")`

is working
