### ISSUE TITLE
run shell empty output

### ISSUE THREAD

**Issue by SpectatorNan** [kareman/SwiftShell#105]
i create a mac app. and i run shell which docker. 
it return stdout is empty string
![image](https://user-images.githubusercontent.com/13959374/162411205-38470900-4ca2-4153-93bf-7b40a2269c61.png)
this code run. 
- which fetch docker path is empty
- absolute run command success
- use run docker command output command not found error

**Comment by kareman** [comment]
It looks like `docker` command path is not in the `PATH` env variable when running the app.

**Comment by SpectatorNan** [comment]
> It looks like `docker` command path is not in the `PATH` env variable when running the app.

I don't know if this is because of permission issues or if this app needs to import system environment variables

This app is a CI and code generation tool. Some operational behaviors depend on other tools, such as docker, go, etc.

**Comment by SpectatorNan** [comment]
The reason is that the path in the APP environment variable is different from the path in the system.

```
static func startLoadEnv() {
        let userHomePath = EnviromentUtils.userHomeDirPath
        let goOutput = SwiftShell.run(bash: "source \(userHomePath)/.zshrc ; echo $PATH")
        var env = SwiftShell.main.env
        env["PATH"] = "\(goOutput.stdout):/usr/local/bin"
        SwiftShell.main.env = env
    }
```
This method can be called when the APP starts to solve this problem

**Comment by kareman** [comment]
Excellent, glad it is working now.
