### ISSUE TITLE
Add to Cocoapods

### ISSUE THREAD

**Issue by h4llow3En** [kareman/SwiftShell#13]

**Comment by kareman** [comment]
Yes that is a good idea. Unfortunately I know nothing about adding projects to CocoaPods. So I'm hoping someone who does will implement this one.

BTW, SwiftShell works very well with  [Carthage](https://github.com/Carthage/Carthage/tree/master/Carthage/Checkouts).

**Comment by h4llow3En** [comment]
The instructions how to create a Pod can be found here:

https://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by kareman** [comment]
Since Apple is making their own Swift Package Manager I'm going to close this one.
