### ISSUE TITLE
run().read()'ing particularly long outputs causes a hang

### ISSUE THREAD

**Issue by master-nevi** [kareman/SwiftShell#15]
Basically NSTask.waitUntilExit() never returns for some reason. Easy to reproduce by calling `cat <some_large_text_file>.txt`

![screen shot 2016-03-02 at 3 09 22 pm](https://cloud.githubusercontent.com/assets/987706/13479009/e2cbbb18-e088-11e5-817d-481237423508.png)

**Comment by kareman** [comment]
Hi, judging by the screenshot it seems like you're using version 1. I get the same error in the latest version (2):

```swift
run("cat","longtext.txt")
```

This function does indeed call `task.waitUntilExit()`. This however does not and works fine:

```swift
runAsync("cat","longtext.txt").stdout.read()
```

**Comment by kareman** [comment]
Postponing `task.waitUntilExit()` until after reading all of the output fixed the problem. I still want to wait until the task has finished just in case it does some work after closing its standard output.

@master-nevi and thanks for reporting this. Please let me know if this fixes the problem for you.
