### ISSUE TITLE
Error while installing (PartialSourceLazySplitSequence)

### ISSUE THREAD

**Issue by tanmayb123** [kareman/SwiftShell#20]
When I try to install SwiftShell, it gives me this error:
"Use of undeclared type 'PartialSourceLazySplitSequence'"
On line 42 of Stream.swift
(For all branches, master, SwiftShell2, and issue-19)

**Comment by kareman** [comment]
Sorry to hear that. I'm on holiday until tomorrow so am not able to check this right away but does this only happen when you run `xcodebuild install`? Does it build and test fine in Xcode? Could you try downloading the entire repository to a new folder and install from there?

**Comment by kareman** [comment]
@tanmayb123 Hi, just cloned the repository to a new folder and `xcodebuild install` ran without problems. Are you still getting this error?

**Comment by tanmayb123** [comment]
Well, actually, I'm just copying the source to the actual project, because it's a command line tool. I never actually run `xcodebuild install`

**Comment by kareman** [comment]
Then there must be some problem with how it is copied into the Xcode project. Can you check that "General/Lazy-split.swift" is being compiled?

**Comment by kareman** [comment]
@tanmayb123 Hi, are you still having this problem?

**Comment by tanmayb123** [comment]
Sorry - How can I check whether or not "General/Lazy-split.swift" is being compiled?

(Again, sorry, I was quite busy for the past few days, now it's a bit better, thanks for your time!)

**Comment by kareman** [comment]
I think the easiest is to locate the file in the list to the left in Xcode, right click and select "Show File Inspector" and verify there is a checkmark in front of the command line tool target under "Target Membership" in the panel that just appeared to the right.

**Comment by tanmayb123** [comment]
Alright, so in Build Phases, under Compile Sources, I can see all files in the "General" folder are NOT being compiled. However, putting the files out of the folder has solved the problem. I can work on #19 now.

However, this raises a new question: How can I compile the sources from inside the folder without having to take them out?

**Comment by kareman** [comment]
Not quite sure what you mean, but if you click the + button under the list in "Compile Sources" you should be able to add any missing files there.

**Comment by kareman** [comment]
Hope that helps, because I'm very interested in hearing if my suggestions in #19 work.

**Comment by tanmayb123** [comment]
I'm unable to add files to compile under "Compile Sources" when the files are in a folder. Maybe I'm doing something wrong?

**Comment by kareman** [comment]
I just added the "General" folder to organise the code better. Since you're including all the source files directly in your own project you can organise them however you like. It's probably easiest to put them all in the same folder.

**Comment by kareman** [comment]
Hi, are you still having this problem and the one in #19?
