### ISSUE TITLE
“No such module” when importing SwiftShell in a playground.

### ISSUE THREAD

**Issue by armdn** [kareman/SwiftShell#21]
I'm installed "successfully" SwiftShell 2.2 but Xcode in playground says after stroke: import SwiftShell - no such module 'SwiftShell'. Framework installed in /Library/Frameworks/ under OS X El Capitan 10.11.5. Xcode 7.3.1.

Also tried old version 1.1 for Xcode 6 on OS X 10.9.5 with the same result. Installed framework to same path /Library/Frameworks/ (also tried on ~/Library/Frameworks), with same error - no such module.

What to do with that??

**Comment by kareman** [comment]
I just tested in a fresh download of SwiftShell, and the playground called "Test area" in the SwiftShell project works fine as long as you build the “SwiftShell” scheme first. if you want to use it from your own playground then that playground must be in a Xcode workspace which also includes the SwiftShell project. And you must also build the “SwiftShell” scheme first.

As far as I know these are the only 2 ways to use a non-Apple framework in a playground.
