### ISSUE TITLE
Minimum deployment target issue on 10.12?

### ISSUE THREAD

**Issue by bryan3000000** [kareman/SwiftShell#23]
Running 10.12.  Framework installed in ~/Library/Frameworks/.  Whenever I run a swift script importing SwiftShell, I get the following error:

./swifttest:4:8: error: module file's minimum deployment target is OS X v10.11: /Users/xxxxx/Library/Frameworks/SwiftShell.framework/Modules/SwiftShell.swiftmodule/x86_64.swiftmodule

I have also tried setting the deployment target on the framework specifically to 10.12 and rebuilding, but it gives the same error, just substituting 10.12.

I realize this could be user error, but I am not sure what at this point.  Any guidance would be appreciated.

**Comment by kareman** [comment]
Hi, I haven't upgraded yet myself but I'm installing 10.12 in a virtual machine now to test this. Which version of Xcode are you using? And which version of swift on the commandline?

**Comment by bryan3000000** [comment]
XCode 8, XCode 8 command-line tools, Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)

I'm actually running the first or second version of the GM of Sierra, build 16A319 - this is a lower build number than the final release, but it won't pull any updates - I don't think this detail should matter.

I did make sure the Swift 3 branch was checked out before compiling.

**Comment by kareman** [comment]
@bryan3000000 Setting the minimum deployment target to 10.9 fixed the problem. I have no idea why.

Can you try the latest commit and see if it works on 10.12 as well?

**Comment by bryan3000000** [comment]
That commit does appear to have fixed the issue on 10.12.  I second your confusion, and would not have thought to do that.  In fact, I had forgotten to add that the import was working just fine as long as you were running swiftshell directly from the command line (as REPL) rather than in a script.  

The only difference I can see is that the compile size is slightly larger with the deployment target set to 10.9.  I assume this difference would be explained by the extra plumbing needed by 10.9 to run Swift.  Maybe there's an issue in Swift 3 that the 10.9 compatibility works around.

**Comment by kareman** [comment]
It seems like a bug, but I have not been able to find much information on it. I also got the same problem on macOS 10.11.
