### ISSUE TITLE
Is there a way to interrupt a shell cmd?

### ISSUE THREAD

**Issue by kdawgwilk** [kareman/SwiftShell#33]
I am creating a CLI tool and need to call out to various shell commands but still want to give the user the ability to interrupt the external cmd that is running to quit the currently running script

**Comment by kareman** [comment]
Yes you can call the stop method:

```
let asynctask = runAsync("cmd", "arg1", "arg2" )
asynctask.stop()
```

**Comment by kdawgwilk** [comment]
Thanks! Was searching through docs but didn't see it right away
