### ISSUE TITLE
How do we pipe?

### ISSUE THREAD

**Issue by patchthecode** [kareman/SwiftShell#34]
` let result = run("ps", "-ax", "|", "grep", "Simulator.app")`

I need to capture the result so that i can run some further regex on it
:/

**Comment by kareman** [comment]
Try this:

```swift
let result = run(bash:"ps -ax | grep Simulator.app")
```

The "|" is handled by the shell, so you need to run it with bash. 

You could also do
```swift
let result = run("ps","-ax").run("grep","Simulator.app")
```
where you get the string output from the first command and use it as input for the second command.

**Comment by patchthecode** [comment]
Thank you.
Awesome library. 
Left a star rating.

**Comment by kareman** [comment]
I'm glad to hear it :).

I'm trying to improve the documentation – please let me know if there's anything you think is missing from the readme or should be described in more detail.
