### ISSUE TITLE
Swift package manager: No such module

### ISSUE THREAD

**Issue by devios1** [kareman/SwiftShell#47]
Hi there, I'm having some difficulty getting a test project compiling with SwiftShell. I'm pretty new to Swift Package Manager so that doesn't help. I wonder if I'm missing something.

Here is my Package.swift file:

```
// swift-tools-version:4.0

import PackageDescription

let package = Package(
    name: "commandlinetest",
    dependencies: [
        .package(url: "https://github.com/kareman/SwiftShell.git", from: "4.0.0")
    ],
    targets: [
        .target(
            name: "commandlinetest",
            dependencies: []),
    ]
)
```

I have a very simple main.swift file that just tries to import SwiftShell, but fails when I try to build it:

Compile Swift Module 'commandlinetest' (1 sources)
/Users/…/commandlinetest/Sources/commandlinetest/main.swift:1:8: error: no such module 'SwiftShell'
import SwiftShell
       ^
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/…/commandlinetest/.build/debug.yaml main

My test project (commandlinetest) was created using "swift package init --type executable". I haven't done anything custom at all yet, but I can't get past this step.

I feel like I must be missing something dumb or something. Any help would be appreciated. I've been banging my head over this for an hour or so.

**Comment by devios1** [comment]
I solved it! Sure enough it was just something dumb: I had forgotten to mention SwiftShell in the **_target_** dependencies.

Got it now!

**Comment by rootscript** [comment]
So just to clarify this works with Swift Package Manger 4, and in Package.swift the following is needed:

```
// swift-tools-version:4.0

import PackageDescription

let package = Package(
    name: "commandlinetest",
    dependencies: [
        .package(url: "https://github.com/kareman/SwiftShell.git", from: "4.0.0"),
        .package(url: "https://github.com/SwiftyJSON/SwiftyJSON.git", from: "4.0.0")
    ],
    targets: [
        .target(
            name: "commandlinetest",
            dependencies: ["SwiftShell", "SwiftyJSON"]),
    ]
)

```

**Comment by devios1** [comment]
Yes exactly. You need to include it in both places: first as the dependency of the package and secondly as a dependency of the target. Then it should be able to be imported and linked.
