### ISSUE TITLE
runAndPrint will not pass an interrupt

### ISSUE THREAD

**Issue by vknabel** [kareman/SwiftShell#48]
When the host program receives an interrupt, `runAndPrint` will still execute, while `runAsync` will pass the interrupt.

```swift
import SwiftShell

main.runAndPrint("yes") // this would indefinitely execute
main.otherRunAndPrint("yes") // this would pass interrupts

extension CommandRunning {
        func otherRunAndPrint(_ executable: String, _ args: Any ...) throws {
                let command = runAsync(executable, args)
                var stdout = context.stdout
                command.stdout.onOutput { $0.write(to: &stdout) }
                var stderror = context.stderror
                command.stderror.onOutput { $0.write(to: &stderror) }
                try command.finish()
        }
}
```

Do you have an idea how to explain this behavior?

When trying this out, I could experience the error mentioned in #45
`runAndPrint` vs `runAsync` from https://github.com/xcodeswift/sake/pull/44#issuecomment-353865937

**Comment by kareman** [comment]
@vknabel Hi, and sorry for the late reply. I'm afraid I don't know what could be causing this. But I have released version 4.0.1, with pull request #45, so at least you shouldn't have that problem anymore.

**Comment by vknabel** [comment]
@kareman Thank you very much! Maybe the stdout will be closed in the latter case as it is handled by a programm which does no longer run? Maybe `runAndPrint` executes the command with the terminal session itself as "owner"?

Would explicitly passing Interrupts to all running commands fall into the responsibility of this project?

**Comment by kareman** [comment]
If it fixes this bug, then yes.
