### ISSUE TITLE
SwiftShell is listed as available for iOS on CocoaPods.org

### ISSUE THREAD

**Issue by syvertsj** [kareman/SwiftShell#50]
Found this on cocoapods.org, searching for a swift application on iOS for running shell applications.

Updated Podfile, ran pod install, SwiftShell is visible in the Pods location in Xcode, and can import SwiftShell in a single ViewController app.
Attempting to invoke run() function is not recognized.
Running with Xcode 9.2 and swift 4.

**Comment by kareman** [comment]
You can’t run shell applications on iOS. Apple won’t allow it.

**Comment by syvertsj** [comment]
That is what I though. Thank you for the response. 
This is coming up on cocoapods.org using "iOS" as a search condition, and it should not be.

**Comment by kareman** [comment]
You’re right, it shouldn’t. The reason it does is I’m using a pretty ugly workaround to allow Swiftshell and Filesmith to use each other’s streams on macOS. So Filesmith imports swiftshell, even on iOS, but uses only 1 source file from it there. I really should find a better way of doing it that avoids importing swiftshell on iOS, but don’t have the time to look into it at the moment.

**Comment by syvertsj** [comment]
Thanks again. 
If you do not mind my asking, I am looking for a 'pod' or way of implementing network testing in iOS, like 'ping', 'nslookup', and 'route'. 
I am not having much luck finding something on cocoapods for that purpose. If you could recommend something I would appreciate it.

**Comment by kareman** [comment]
No idea, I'm afraid.

**Comment by kareman** [comment]
[#if canImport](https://github.com/apple/swift-evolution/blob/master/proposals/0075-import-test.md) will be available in Swift 4.1, I _think_ that can be used as a better solution.
