### ISSUE TITLE
NSConcreteTask launchWithDictionary: crash

### ISSUE THREAD

**Issue by xinlehou** [kareman/SwiftShell#51]
Crashed Thread:        1  Dispatch queue: com.find.timesync

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff84a482cb __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fff9985348d objc_exception_throw + 48
2   CoreFoundation                      0x00007fff84ac6c3d +[NSException raise:format:] + 205
3   Foundation                          0x00007fff864712e6 -[NSConcreteTask launchWithDictionary:] + 2518
4   SwiftShell                          0x0000000105ade1f9 _TToFE10SwiftShellCSo7Process15launchThrowablyfzT_T_ + 41
5   SwiftShell                          0x0000000105adea43 _TFC10SwiftShell9RunOutputcfT6launchCS_12AsyncCommand_S0_ + 147
6   SwiftShell                          0x0000000105ae2874 _TTSf4gs_g_n_n___TTSg5C10SwiftShell11MainContextS0_S_14CommandRunningS____TFE10SwiftShellPS_14CommandRunning3runfTSSGSaP__13combineOutputSb_CS_9RunOutput + 820
7   SwiftShell                          0x0000000105adbaf8 _TTSf4gs_n___TF10SwiftShell3runFT4bashSS13combineOutputSb_CS_9RunOutput + 264
8   SwiftShell                          0x0000000105adb93f _TF10SwiftShell3runFT4bashSS13combineOutputSb_CS_9RunOutput + 15
9   find                                0x0000000103587568 _TTSf4d___TZFC4find10AppManager7syncNTPfT_GSqSd_ + 296
10  find                                0x000000010348b79d _TFC4find18FindTimeSyncServer11loopProcessfT_T_ + 301
11  find                                0x000000010348bacb _TFFFC4find18FindTimeSyncServer11loopProcessFT_T_U_FT_T_U_FT_T_ + 43
12  libdispatch.dylib                   0x00007fff9a10b524 _dispatch_call_block_and_release + 12
13  libdispatch.dylib                   0x00007fff9a1028fc _dispatch_client_callout + 8
14  libdispatch.dylib                   0x00007fff9a1189a0 _dispatch_queue_serial_drain + 896
15  libdispatch.dylib                   0x00007fff9a10b306 _dispatch_queue_invoke + 1046
16  libdispatch.dylib                   0x00007fff9a111020 _dispatch_queue_override_invoke + 369
17  libdispatch.dylib                   0x00007fff9a1046b5 _dispatch_root_queue_drain + 476
18  libdispatch.dylib                   0x00007fff9a10448c _dispatch_worker_thread3 + 99
19  libsystem_pthread.dylib             0x00007fff9a3515a2 _pthread_wqthread + 1299
20  libsystem_pthread.dylib             0x00007fff9a35107d start_wqthread + 13

**Comment by kareman** [comment]
Ok... so what is the code that is crashing?

**Comment by kareman** [comment]
Since there is no information to work with here I’m closing this issue. Feel free to reopen it if you want to add the code that is causing this crash.
