### ISSUE TITLE
Dynamically generated argument arrays

### ISSUE THREAD

**Issue by ileitch** [kareman/SwiftShell#53]
SwiftShell uses variadic arguments all over the place, making it unfrienfly for dynamically generated commands since Swift currently doesn't support splatting arrays. The only workaround is to build up a string and use `run(bash:`).

It'd be nice if SwiftShell also supported array arguments for all methods that currently accept only variadic. Thanks!

**Comment by kareman** [comment]
But SwiftShell supports splatting arrays. This should work:

```swift
let array = ["But", "we", "are"]
try runAndPrint("echo", array, array.count + 2, "arguments")
// echo But we are 5 arguments
```

**Comment by ileitch** [comment]
Ah, sorry I missed that. Thank you.
