### ISSUE TITLE
process.terminate() has not been implemented on Linux

### ISSUE THREAD

**Issue by Ponyboy47** [kareman/SwiftShell#59]
I'm receiving this error calling `command.stop()` on Linux:

Fatal error: terminate() is not yet implemented: file Foundation/Process.swift, line 464

I'll make the pull request, but would you recommend marking it as unavailable on Linux with:
```swift
@available(Linux, unavailable, message: "The terminate() function has not been implemented on Linux")
```

or to use a compiler flag:
```swift
#if os(macOS)
...
#endif
```

**Comment by kareman** [comment]
Yes, Foundation on Linux has a lot of catching up to do. I think it would be best to mark it as unavailable, as that should provide better error messages when trying to use the method on Linux.
