### ISSUE TITLE
Changing current directory

### ISSUE THREAD

**Issue by IgorMuzyka** [kareman/SwiftShell#65]
Hey, i get that i should use `main.currentdirectory` instead of `run("pwd")` but how do i change the current directory so that when my terminal app is exited the user will end up in a place he selected from inside the app?

**Comment by kareman** [comment]
I don’t think that is possible. I’ve never seen a shell script in any language change the directory of the calling terminal session. 

For more info see https://stackoverflow.com/questions/255414/why-doesnt-cd-work-in-a-shell-script

Note that the “source” solution mentioned there only works with bash scripts (or whatever interpreter you’re using).

**Comment by IgorMuzyka** [comment]
That's a pity 😕

**Comment by ERbittuu** [comment]
How can I go to the parent directory?

main.currentdirectory = "New" will be going child dir

**Comment by kareman** [comment]
You need to give the full path of the directory, beginning with ‘/‘. “New” refers to a child directory because it does not start with a ‘/‘.
