### ISSUE TITLE
Printing in colours

### ISSUE THREAD

**Issue by kareman** [kareman/SwiftShell#7]
See https://github.com/mikeash/memorydumper 
Specifically TermPrinter.

**Comment by beltex** [comment]
[PrettyColors](https://github.com/jdhealy/PrettyColors) could be helpful for this as well.

**Comment by kareman** [comment]
Oh cool, I'll look into that. Thanks.

**Comment by beltex** [comment]
np!

**Comment by kareman** [comment]
This is probably better handled by other frameworks.
