### ISSUE TITLE
Gatekeeper and SwiftShell

### ISSUE THREAD

**Issue by jhoughjr** [kareman/SwiftShell#72]
Idk if this is SwiftShell related or not but in any app I've used it in Gatekeeper rejects the app.
"
File /Users/jimmyhoughjr/Downloads/Ghostnote2-10.app/Contents/Resources/ghostengine.app/Contents/MacOS/../Frameworks/SwiftShell.framework/Versions/A/SwiftShell failed on rPathCmd /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib

"

I'm not sure why this is happening though.

**Comment by kareman** [comment]
I haven’t heard if this error before. Are you using other 3rd party swift frameworks in the same apps? Could you try enable signing for the Swiftshell framework target?

**Comment by jhoughjr** [comment]
Where is the setting for that again? I'm not seeing it. Using Xcode 10. I just build it via Carthage and link and embed it.

**Comment by jhoughjr** [comment]
code sign on copy is selected.
