### ISSUE TITLE
Cancel with Ctrl-C

### ISSUE THREAD

**Issue by peacemoon** [kareman/SwiftShell#77]
I have a list of long running bash commands that I execute using `runAndPrint(bash: )` in a for loop. I try to terminate the execution using Ctrl-C but somehow the new command gets executed again. I assume that I can only terminate some of the subcommands but not the whole process. Any idea how can I listen for Ctrl-C in my code and cancel the whole process programmatically?

**Comment by kareman** [comment]
That's strange, I tried running this:

```swift
import SwiftShell

for i in 1 ... 5 {
	print(i)
	try runAndPrint(bash: "sleep 5")
}
```

and the entire application was terminated when I pressed Ctrl-C:

```bash
/tmp/cancel> swift run
[3/3] Linking cancel
1
2
^C
/tmp/cancel> 
```

Could you share the code in the for-loop?

**Comment by peacemoon** [comment]
Ok strange, it seems that the application is really terminated and only the output is still buffered and printed out afterward.

Sorry for the confusion.

**Comment by kareman** [comment]
No problem. Just to be clear, I think what happens is that when you press CTRL-C the _Swift_ application is terminated. The bash command that has already been launched will continue uninterrupted in its own separate process.

**Comment by peacemoon** [comment]
@kareman thank you for your explanation. Do you have any idea how I can terminate also all subprocesses in this case?

**Comment by kareman** [comment]
I think you can do [this](https://stackoverflow.com/a/45714258/96587) to be notified when the user presses ctrl-c. 

When running commands you need to use runAsync or runAsyncAndPrint and store it in a variable. So it can be cancelled later with `.stop()`. 

Let me know if it works, it would be nice to have the notification functionality in SwiftShell.

**Comment by Ponyboy47** [comment]
I've used IBM's [BlueSignals](https://github.com/IBM-Swift/BlueSignals) framework to do this in my own things.
