### ISSUE TITLE
Xcode 12 beta / Swift 5.3 not building

### ISSUE THREAD

**Issue by devdrey** [kareman/SwiftShell#82]
Hey,
I discovered this package is not able to build with Xcode 12 beta and Swift 5.3.

There is a segmentation fault when trying to compile. See the exported error.

[Build SwiftShell_2020-06-29T12-06-02.txt](https://github.com/kareman/SwiftShell/files/4845579/Build.SwiftShell_2020-06-29T12-06-02.txt)

Since it's a segmentation fault in an early stage of compiling and I'm using an XCode 12 beta it might be this issue will not be present anymore in later beta releases. But anyway I wanted to let you know, so you are aware of this issue. ✌️

**Comment by kareman** [comment]
Thanks for the heads up. I haven’t downloaded the beta yet, I normally wait until at least beta 2. Once that is out I will try to compile and see if there is anything I can do about it if the problem is still there.

**Comment by arguiot** [comment]
@kareman Just wanted to let you know that Xcode beta 2 is out

**Comment by kareman** [comment]
Yes I tested SwiftShell with it just now and the error is still there. I’ll see if I can find a workaround today.

**Comment by kareman** [comment]
Hi, the "Swift5.3" branch should work in Xcode 12.

**Comment by devdrey** [comment]
Hey THX,
I can verify that his build s with Xcode 12 and also still with xcode 11.5!
