### ISSUE TITLE
Allow `run` to take an array

### ISSUE THREAD

**Issue by ryanmeisters** [kareman/SwiftShell#98]
I think it would be nice to provide an array variant of the the `run` methods in addition to the APIs with variadic args. This would make code less awkward in cases where argument lists are generated programatically

I might be able to take a crack at it if you think it would be appropriate.

Thanks for the great package!

**Comment by ryanmeisters** [comment]
Oh I see now that the args get flattened so this isn’t needed. Closing 😇

**Comment by kareman** [comment]
They already take arrays. Try it :)
